sudo: required
language: go
go_import_path: github.com/colinmarc/hdfs
go: 1.x
env:
- PLATFORM=hdp2
- PLATFORM=cdh5
- PLATFORM=cdh6
- PLATFORM=cdh6 KERBEROS=true RPC_PROTECTION=authentication DATA_TRANSFER_PROTECTION=authentication
- PLATFORM=cdh6 KERBEROS=true RPC_PROTECTION=integrity DATA_TRANSFER_PROTECTION=integrity
- PLATFORM=cdh6 KERBEROS=true RPC_PROTECTION=privacy DATA_TRANSFER_PROTECTION=privacy
- PLATFORM=cdh6 KERBEROS=true RPC_PROTECTION=privacy DATA_TRANSFER_PROTECTION=privacy AES=true
before_install:
- export GO111MODULE=on # Travis installs into $GOPATH/src, which disables module support by default.
install:
- git clone https://github.com/sstephenson/bats $HOME/bats
- mkdir -p $HOME/bats/build
- "$HOME/bats/install.sh $HOME/bats/build"
- export PATH="$PATH:$HOME/bats/build/bin"
- ./travis-setup.sh $PLATFORM
before_script:
- export HADOOP_CONF_DIR="/etc/hadoop/conf"
- find internal/protocol -name *.pb.go | xargs touch # so make doesn't try to regen protobuf files
script: make test
after_failure: find /var/log/hadoop-hdfs | xargs cat
before_deploy: make release
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: MhNMuDo2ptwA3pXVJfIppskC0/Tg2pyoBcK/A1MAh8ifRrcw3HA2HjOgOj8HxE136aWLW90vnO1rpPRS60lyQikKyJtn2bg0/Earyz40bdQIxpxjeGyzS2yGdyuORivAoBqRMNXDBeMYjwIB/D/BkBJFRjk+VKn6hy6XgalbHcA=
  file: gohdfs-*.tar.gz
  file_glob: true
  on:
    repo: colinmarc/hdfs
    tags: true
    all_branches: true
    condition: $PLATFORM = hdp2
cache:
  directories:
  - $HOME/.cache/go-build
  - $GOPATH/pkg/mod
