language: go
go_import_path: github.com/colinmarc/hdfs
go:
  - 1.4
  - 1.5
before_install:
  - git clone https://github.com/sstephenson/bats $HOME/bats
  - mkdir -p $HOME/bats/build
  - $HOME/bats/install.sh $HOME/bats/build
  - export PATH="$PATH:$HOME/bats/build/bin"
install: make get-deps
env:
  - HADOOP_DISTRO=cdh
  - HADOOP_DISTRO=hdp
before_script:
  - export NN_PORT=9000
  - export HADOOP_NAMENODE="localhost:$NN_PORT"
  - export HADOOP_HOME="$HOME/hadoop-$HADOOP_DISTRO"
  - ./setup_test_env.sh
script:
  - make test
  - cat minicluster.log
sudo: false
cache:
  - $HADOOP_HOME
  - $HOME/bats
